import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

/// Hand-written localization shim.
///
/// In a typical Flutter project these strings would be code-generated by
/// `flutter gen-l10n` from `lib/l10n/app_*.arb`. Because this task ships
/// without the Flutter toolchain available, the ARB files (en/th/zh/ja)
/// remain the source of truth and this class mirrors them verbatim.
///
/// If/when `gen-l10n` is wired into the build, delete this file and replace
/// it with `import 'package:flutter_gen/gen_l10n/app_localizations.dart';`.
class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[
    Locale('en'),
    Locale('th'),
    Locale('zh'),
    Locale('ja'),
  ];

  static const localizationsDelegates = <LocalizationsDelegate<dynamic>>[
    _AppLocalizationsDelegate(),
    GlobalMaterialLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
  ];

  static AppLocalizations of(BuildContext context) {
    final l = Localizations.of<AppLocalizations>(context, AppLocalizations);
    assert(l != null, 'AppLocalizations missing — wire delegates in MaterialApp.');
    return l!;
  }

  String _t(String key) {
    final table = _strings[locale.languageCode] ?? _strings['en']!;
    return table[key] ?? _strings['en']![key] ?? key;
  }

  String get appTitle => _t('appTitle');
  String get welcomeGreeting => _t('welcomeGreeting');
  String get welcomePrompt => _t('welcomePrompt');
  String get startOrder => _t('startOrder');
  String get scanQrCode => _t('scanQrCode');
  String get footerVersion => _t('footerVersion');
  String get languageTitle => _t('languageTitle');
  String get chooseLanguage => _t('chooseLanguage');
  String get next => _t('next');
  String get back => _t('back');
  String get categoriesTitle => _t('categoriesTitle');
  String get chooseCategory => _t('chooseCategory');
  String get menuListSearchHint => _t('menuListSearchHint');
  String get addToCart => _t('addToCart');
  String get quantity => _t('quantity');
  String get yourCart => _t('yourCart');
  String get promoCodeHint => _t('promoCodeHint');
  String get subtotal => _t('subtotal');
  String get serviceCharge => _t('serviceCharge');
  String get tax7Pct => _t('tax7Pct');
  String get discount => _t('discount');
  String get total => _t('total');
  String get checkout => _t('checkout');
  String get checkoutTitle => _t('checkoutTitle');
  String get payWith => _t('payWith');
  String get paymentCreditCard => _t('paymentCreditCard');
  String get paymentApplePay => _t('paymentApplePay');
  String get paymentWallet => _t('paymentWallet');
  String get paymentCash => _t('paymentCash');
  String get summary => _t('summary');
  String get payNow => _t('payNow');
  String get thankYou => _t('thankYou');
  String get orderPlacedSuccess => _t('orderPlacedSuccess');
  String get orderNumberLabel => _t('orderNumberLabel');
  String get continueAction => _t('continueAction');
  String get orderStatusTitle => _t('orderStatusTitle');
  String get etaLabel => _t('etaLabel');
  String get stepReceived => _t('stepReceived');
  String get stepPreparing => _t('stepPreparing');
  String get stepReady => _t('stepReady');
  String get callStaff => _t('callStaff');
  String get addSide => _t('addSide');
  String get required => _t('required');
  String get modifierGroupRequired => _t('modifierGroupRequired');
  String get tableLabel => _t('tableLabel');
  String get manualTableEntry => _t('manualTableEntry');
  String get tableCodeHint => _t('tableCodeHint');
  String get submit => _t('submit');
  String get cameraPermissionDenied => _t('cameraPermissionDenied');
  String get tryAgain => _t('tryAgain');
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'th', 'zh', 'ja'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

// Inline mirror of the ARB files. Source of truth lives in lib/l10n/app_*.arb.
const Map<String, Map<String, String>> _strings = {
  'en': {
    'appTitle': 'Monti',
    'welcomeGreeting': "Hi! I'm Monti",
    'welcomePrompt': 'What would you like to do?',
    'startOrder': 'START ORDER',
    'scanQrCode': 'SCAN QR CODE',
    'footerVersion': 'v1.0 · powered by AI',
    'languageTitle': 'Language',
    'chooseLanguage': 'Choose your language',
    'next': 'NEXT',
    'back': 'Back',
    'categoriesTitle': 'Categories',
    'chooseCategory': 'Choose a Category',
    'menuListSearchHint': 'Search dishes...',
    'addToCart': 'ADD TO CART',
    'quantity': 'Quantity',
    'yourCart': 'Your Cart',
    'promoCodeHint': 'Promo code',
    'subtotal': 'Subtotal',
    'serviceCharge': 'Service Charge',
    'tax7Pct': 'Tax 7%',
    'discount': 'Discount',
    'total': 'TOTAL',
    'checkout': 'CHECKOUT',
    'checkoutTitle': 'Checkout',
    'payWith': 'Pay with',
    'paymentCreditCard': 'Credit Card',
    'paymentApplePay': 'Apple Pay',
    'paymentWallet': 'Wallet',
    'paymentCash': 'Cash',
    'summary': 'Summary',
    'payNow': 'PAY NOW',
    'thankYou': 'Thank You',
    'orderPlacedSuccess': 'Your order has been placed successfully',
    'orderNumberLabel': 'Order #',
    'continueAction': 'CONTINUE',
    'orderStatusTitle': 'Order Status',
    'etaLabel': 'ETA',
    'stepReceived': 'Order Received',
    'stepPreparing': 'Preparing',
    'stepReady': 'Ready',
    'callStaff': 'CALL STAFF',
    'addSide': 'Add Side',
    'required': 'required',
    'modifierGroupRequired': 'Please choose one option',
    'tableLabel': 'Table',
    'manualTableEntry': 'Enter table code',
    'tableCodeHint': 'Table code (e.g. A12)',
    'submit': 'SUBMIT',
    'cameraPermissionDenied': 'Camera permission denied',
    'tryAgain': 'TRY AGAIN',
  },
  'th': {
    'appTitle': 'มอนติ',
    'welcomeGreeting': 'สวัสดี! ฉันชื่อมอนติ',
    'welcomePrompt': 'คุณต้องการทำอะไร?',
    'startOrder': 'เริ่มสั่งอาหาร',
    'scanQrCode': 'สแกน QR',
    'footerVersion': 'v1.0 · ขับเคลื่อนด้วย AI',
    'languageTitle': 'ภาษา',
    'chooseLanguage': 'เลือกภาษาของคุณ',
    'next': 'ถัดไป',
    'back': 'ย้อนกลับ',
    'categoriesTitle': 'หมวดหมู่',
    'chooseCategory': 'เลือกหมวดหมู่',
    'menuListSearchHint': 'ค้นหาเมนู...',
    'addToCart': 'เพิ่มลงตะกร้า',
    'quantity': 'จำนวน',
    'yourCart': 'ตะกร้าของคุณ',
    'promoCodeHint': 'รหัสโปรโมชั่น',
    'subtotal': 'ยอดรวม',
    'serviceCharge': 'ค่าบริการ',
    'tax7Pct': 'ภาษี 7%',
    'discount': 'ส่วนลด',
    'total': 'รวมทั้งหมด',
    'checkout': 'ชำระเงิน',
    'checkoutTitle': 'ชำระเงิน',
    'payWith': 'ชำระด้วย',
    'paymentCreditCard': 'บัตรเครดิต',
    'paymentApplePay': 'Apple Pay',
    'paymentWallet': 'วอลเล็ต',
    'paymentCash': 'เงินสด',
    'summary': 'สรุป',
    'payNow': 'ชำระเงิน',
    'thankYou': 'ขอบคุณค่ะ',
    'orderPlacedSuccess': 'คำสั่งซื้อของคุณถูกส่งเรียบร้อยแล้ว',
    'orderNumberLabel': 'เลขที่ออเดอร์',
    'continueAction': 'ต่อไป',
    'orderStatusTitle': 'สถานะคำสั่งซื้อ',
    'etaLabel': 'เวลาโดยประมาณ',
    'stepReceived': 'รับคำสั่งซื้อแล้ว',
    'stepPreparing': 'กำลังเตรียม',
    'stepReady': 'พร้อมเสิร์ฟ',
    'callStaff': 'เรียกพนักงาน',
    'addSide': 'เพิ่มเครื่องเคียง',
    'required': 'จำเป็น',
    'modifierGroupRequired': 'กรุณาเลือกหนึ่งตัวเลือก',
    'tableLabel': 'โต๊ะ',
    'manualTableEntry': 'ใส่รหัสโต๊ะ',
    'tableCodeHint': 'รหัสโต๊ะ (เช่น A12)',
    'submit': 'ส่ง',
    'cameraPermissionDenied': 'ไม่ได้รับอนุญาตให้ใช้กล้อง',
    'tryAgain': 'ลองอีกครั้ง',
  },
  'zh': {
    'appTitle': '蒙提',
    'welcomeGreeting': '你好！我是蒙提',
    'welcomePrompt': '您想做什么？',
    'startOrder': '开始点餐',
    'scanQrCode': '扫描二维码',
    'footerVersion': 'v1.0 · 由 AI 驱动',
    'languageTitle': '语言',
    'chooseLanguage': '选择您的语言',
    'next': '下一步',
    'back': '返回',
    'categoriesTitle': '分类',
    'chooseCategory': '选择分类',
    'menuListSearchHint': '搜索菜品...',
    'addToCart': '加入购物车',
    'quantity': '数量',
    'yourCart': '您的购物车',
    'promoCodeHint': '优惠码',
    'subtotal': '小计',
    'serviceCharge': '服务费',
    'tax7Pct': '税 7%',
    'discount': '折扣',
    'total': '总计',
    'checkout': '结账',
    'checkoutTitle': '结账',
    'payWith': '支付方式',
    'paymentCreditCard': '信用卡',
    'paymentApplePay': 'Apple Pay',
    'paymentWallet': '钱包',
    'paymentCash': '现金',
    'summary': '摘要',
    'payNow': '立即支付',
    'thankYou': '谢谢您',
    'orderPlacedSuccess': '您的订单已成功提交',
    'orderNumberLabel': '订单号',
    'continueAction': '继续',
    'orderStatusTitle': '订单状态',
    'etaLabel': '预计时间',
    'stepReceived': '已接收订单',
    'stepPreparing': '准备中',
    'stepReady': '已就绪',
    'callStaff': '呼叫服务员',
    'addSide': '添加配菜',
    'required': '必选',
    'modifierGroupRequired': '请选择一项',
    'tableLabel': '餐桌',
    'manualTableEntry': '输入桌号',
    'tableCodeHint': '桌号 (例如 A12)',
    'submit': '提交',
    'cameraPermissionDenied': '相机权限被拒绝',
    'tryAgain': '重试',
  },
  'ja': {
    'appTitle': 'モンティ',
    'welcomeGreeting': 'こんにちは！モンティです',
    'welcomePrompt': 'ご注文はいかがですか？',
    'startOrder': '注文を開始',
    'scanQrCode': 'QR コード スキャン',
    'footerVersion': 'v1.0 · AI 搭載',
    'languageTitle': '言語',
    'chooseLanguage': '言語を選択してください',
    'next': '次へ',
    'back': '戻る',
    'categoriesTitle': 'カテゴリ',
    'chooseCategory': 'カテゴリを選択',
    'menuListSearchHint': 'メニューを検索...',
    'addToCart': 'カートに追加',
    'quantity': '数量',
    'yourCart': 'あなたのカート',
    'promoCodeHint': 'プロモーションコード',
    'subtotal': '小計',
    'serviceCharge': 'サービス料',
    'tax7Pct': '税 7%',
    'discount': '割引',
    'total': '合計',
    'checkout': 'お会計',
    'checkoutTitle': 'お会計',
    'payWith': 'お支払い方法',
    'paymentCreditCard': 'クレジットカード',
    'paymentApplePay': 'Apple Pay',
    'paymentWallet': 'ウォレット',
    'paymentCash': '現金',
    'summary': 'サマリー',
    'payNow': '今すぐ支払う',
    'thankYou': 'ありがとうございます',
    'orderPlacedSuccess': 'ご注文を承りました',
    'orderNumberLabel': '注文番号',
    'continueAction': '続ける',
    'orderStatusTitle': '注文状況',
    'etaLabel': '予想時間',
    'stepReceived': '注文受付',
    'stepPreparing': '準備中',
    'stepReady': '準備完了',
    'callStaff': 'スタッフを呼ぶ',
    'addSide': 'サイド追加',
    'required': '必須',
    'modifierGroupRequired': '一つお選びください',
    'tableLabel': 'テーブル',
    'manualTableEntry': 'テーブル番号を入力',
    'tableCodeHint': 'テーブル番号 (例: A12)',
    'submit': '送信',
    'cameraPermissionDenied': 'カメラへのアクセスが拒否されました',
    'tryAgain': '再試行',
  },
};
